### ISSUE TITLE
Tool - Deleting source files from the asset manager results in an error

### ISSUE THREAD

**Issue by Pjmisz** [GameOverture/HarmonyEngine#145]
Deleting cpp and h files from the asset manager will pop up an error in the process of deletion. The files will be removed from the tool, but you need delete them from the explorer, source meta and cmakelist for them to be properly removed. (This might only happen to files that are within a folder. I haven't tested files sitting at the parent directory, but I remember that working during the initial tests.)

**Comment by GameOverture** [comment]
Fixed at some point
